### ISSUE TITLE
Documentation: Cargo installation instructions

### ISSUE THREAD

**Issue by ghost** [paradigmxyz/mesc#7]
Hey @sslivkoff,

In the [quickstart section](https://github.com/paradigmxyz/mesc/tree/main) of the README, it suggests using the command `cargo install mesc` to install mesc-cli. However, it appears that this has no binaries, and thus, the installation fails with the error message:

> error: there is nothing to install in `mesc v0.1.1`, because it has no binaries
cargo install is only for installing programs and can't be used with libraries.
To use a library crate, add it as a dependency to a Cargo project with `cargo add`.

I figured it was just a typo and replaced it with `mesc_cli`.

PR: https://github.com/paradigmxyz/mesc/pull/6

**Comment by sslivkoff** [comment]
good find. your pr looks right except it should be `mesc_cli` instead of `mesc-cli`

did you mean to delete it?
